#on:
#  push:
#    branches:
#    - main

#name: Test 10

#jobs:
#  build_and_deploy:
#    name: test 10
#    runs-on: ubuntu-latest
#    environment: production
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#      - uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --release --all-features
#      - uses: burnett01/rsync-deployments@5.1
#        with:
#          switches: -avzr --delete
#          path: ./target/release/meta
#          remote_path: ${{ secrets.SERVER_DEPLOY_PATH }}
#          remote_host: ${{ secrets.SERVER_HOST }}
#          remote_user: ${{ secrets.SERVER_USER }}
#          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
#          remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
      #- name: Commit report
      #  run: |
      #    git config --global user.name 'interesnij'
      #    git config --global user.email 'ochkarik1983@mail.ru'
      #    git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/getnetwork
      #    git add -A
      #    git commit -am "Automated report"
      #    git push
